languageCode = "en-us"
title = "Gripping Golf Podcast"
baseURL = ""
theme = "hugo-theme-massively"
googleanalytics = "UA-157011848-1"
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

[params.forms]
formID="1FAIpQLSdnX3gQaf7HHgXdXoyQXeAtPzdMSum7HJCrdbCrdzJyc24wIA/"
Name="entry.895563655"
Email Address="entry.772189125"
Subject="entry.203645991"
Message="entry.190021963"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = "true"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"